language: ruby

# Apparently sudo is required to test on Rubinius and JRuby-head
sudo: required

# See https://docs.travis-ci.com/user/languages/ruby/#Rubinius
dist: trusty

rvm:
  # MRI
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 1.9.3
  - 1.8.7
  - ree
  # JRuby
  - jruby-head
  - jruby-9.2
  - jruby-9.1
  - jruby-9.0
  # Rubinius
  - rbx-3
  # Truffleruby
  - truffleruby-head
  - truffleruby
  - truffleruby-20.2.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby-head
    - rvm: rbx-3
  fast_finish: true
