# Use container-based infrastructure
sudo: false
language: ruby
# Travis bug, see https://github.com/bundler/bundler/pull/3559
before_install: gem update bundler
cache: bundler
rvm:
  - ruby-head
  - 2.3.3 # Travis lacking 2.3 alias, see https://github.com/travis-ci/travis-ci/issues/5361
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - jruby-head
  - jruby-19mode
  - jruby-18mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-18mode # until we figure out failure in `bundle exec`, which is not our problem
  fast_finish: true
